"""initial schema and rls

Revision ID: 0001
Revises:
Create Date: 2026-09-09

Task 6（V2 Phase 1）：30 张表由 autogenerate 自 backend/v2/models 元数据生成；
手工追加：4 条循环外键补建、DB 角色、owner 上下文函数、表级授权白名单
（Database Design §3.1）、owner/revision/report RLS 策略；experts/skills 为
owner+发布可见性特例（终审 F2）。
downgrade 末尾 DROP SCHEMA app CASCADE（函数随 schema 删除；角色保留，幂等创建；
policy 均表级作用域，随 DROP TABLE 一并清除，无显式 policy DROP）。
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column("route", sa.String(length=300), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("subject_hash", "route", "key", name="idempotency_route_key"),
    )
    op.create_table(
        "platform_slots",
        sa.Column("slot_no", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('free', 'leased')", name=op.f("ck_platform_slots_state_enum")
        ),
        sa.PrimaryKeyConstraint("slot_no", name=op.f("pk_platform_slots")),
    )
    op.create_index(
        "ix_platform_slots_state_leased_until",
        "platform_slots",
        ["state", "leased_until"],
        unique=False,
    )
    op.create_index("ix_platform_slots_task_id", "platform_slots", ["task_id"], unique=False)
    op.create_table(
        "platform_storage",
        sa.Column("singleton", sa.Boolean(), nullable=False),
        sa.Column("retained_storage_bytes", sa.BigInteger(), nullable=False),
        sa.Column("max_retained_storage_bytes", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("singleton", name=op.f("ck_platform_storage_singleton_true")),
        sa.PrimaryKeyConstraint("singleton", name=op.f("pk_platform_storage")),
    )
    op.create_table(
        "provider_catalog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("allowed_host", sa.String(length=253), nullable=False),
        sa.Column("path_prefix", sa.String(length=200), nullable=False),
        sa.Column("models", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("healthcheck_method", sa.String(length=10), nullable=False),
        sa.Column("healthcheck_path", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "allowed_host NOT LIKE '%://%' AND allowed_host NOT LIKE '%@%' "
            "AND allowed_host NOT LIKE '%/%'",
            name=op.f("ck_provider_catalog_allowed_host_shape"),
        ),
        sa.CheckConstraint(
            "healthcheck_method IN ('GET', 'HEAD')",
            name=op.f("ck_provider_catalog_healthcheck_method_enum"),
        ),
        sa.CheckConstraint(
            "healthcheck_path LIKE '/%' AND healthcheck_path NOT LIKE '%..%'",
            name=op.f("ck_provider_catalog_healthcheck_path_shape"),
        ),
        sa.CheckConstraint(
            "path_prefix LIKE '/%' AND path_prefix NOT LIKE '%..%'",
            name=op.f("ck_provider_catalog_path_prefix_shape"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_catalog")),
    )
    op.create_table(
        "rate_limit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=60), nullable=False),
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_events")),
    )
    op.create_index(
        "ix_rate_limit_scope_subject_time",
        "rate_limit_events",
        ["scope", "subject_hash", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "tool_catalog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_catalog")),
        sa.UniqueConstraint("tool_id", "version", name="uq_tool_catalog_id_version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mfa_secret_enc", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "deleted_at IS NULL OR status = 'deleted'", name=op.f("ck_users_deleted_consistency")
        ),
        sa.CheckConstraint("role IN ('user', 'admin')", name=op.f("ck_users_role_enum")),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'suspended', 'deleting', 'deleted')",
            name=op.f("ck_users_status_enum"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "account_action_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('email_verify', 'password_reset', 'deletion_cancel')",
            name=op.f("ck_account_action_tokens_purpose_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_account_action_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_action_tokens")),
    )
    op.create_index(
        op.f("ix_account_action_tokens_token_hash"),
        "account_action_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "content_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("target_revision_id", sa.Uuid(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('expert_revision', 'skill_revision')",
            name=op.f("ck_content_reviews_target_type_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_content_reviews_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_reviews")),
    )
    op.create_index(
        "ix_content_reviews_target_hash",
        "content_reviews",
        ["target_revision_id", "content_sha256"],
        unique=False,
    )
    op.create_table(
        "email_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("payload_ciphertext", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("lease_owner", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('invitation', 'email_verify', 'password_reset', 'deletion_cancel')",
            name=op.f("ck_email_outbox_purpose_enum"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'sent', 'delivery_failed')",
            name=op.f("ck_email_outbox_state_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_outbox_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_outbox")),
    )
    op.create_table(
        "experts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("published_revision_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_experts_status_enum")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_experts_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experts")),
    )
    op.create_index(op.f("ix_experts_owner_id"), "experts", ["owner_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_invitations_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
    )
    op.create_index(
        "invitations_one_open_email",
        "invitations",
        ["email"],
        unique=True,
        postgresql_where=sa.text("consumed_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("target_revision_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'dismissed', 'actioned')", name=op.f("ck_reports_status_enum")
        ),
        sa.CheckConstraint(
            "target_type IN ('expert_revision', 'skill_revision', 'message')",
            name=op.f("ck_reports_target_type_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_table(
        "skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("published_revision_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_skills_status_enum")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_skills_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    op.create_index(op.f("ix_skills_owner_id"), "skills", ["owner_id"], unique=False)
    op.create_table(
        "usage_daily",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("tasks_started", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_usage_daily_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_daily")),
        sa.UniqueConstraint("user_id", "day", name="uq_usage_daily_user_day"),
    )
    op.create_table(
        "user_entitlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entitlement", sa.String(length=40), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "entitlement IN ('expert_author')", name=op.f("ck_user_entitlements_entitlement_enum")
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_user_entitlements_granted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_entitlements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_entitlements")),
    )
    op.create_index(
        "one_active_entitlement",
        "user_entitlements",
        ["user_id", "entitlement"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "user_providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("key_ciphertext", sa.Text(), nullable=False),
        sa.Column("dek_wrapped", sa.Text(), nullable=False),
        sa.Column("key_last4", sa.String(length=4), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_user_providers_status_enum")
        ),
        sa.CheckConstraint("length(key_last4) = 4", name=op.f("ck_user_providers_key_last4_len")),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["provider_catalog.id"],
            name=op.f("fk_user_providers_catalog_id_provider_catalog"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_providers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_providers")),
    )
    op.create_index(op.f("ix_user_providers_user_id"), "user_providers", ["user_id"], unique=False)
    op.create_index(
        "uq_user_providers_one_default",
        "user_providers",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    op.create_table(
        "user_quota_usage",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("active_tasks", sa.Integer(), nullable=False),
        sa.Column("running_tasks", sa.Integer(), nullable=False),
        sa.Column("retained_storage_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_quota_usage_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_quota_usage")),
    )
    op.create_table(
        "user_quotas",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("max_daily_tasks", sa.Integer(), nullable=False),
        sa.Column("max_active_tasks", sa.Integer(), nullable=False),
        sa.Column("max_running_tasks", sa.Integer(), nullable=False),
        sa.Column("max_retained_storage_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_quotas_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_quotas")),
    )
    op.create_table(
        "expert_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("expert_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("content_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_review', 'approved', "
            "'rejected', 'published', 'archived')",
            name=op.f("ck_expert_revisions_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["expert_id"],
            ["experts.id"],
            name=op.f("fk_expert_revisions_expert_id_experts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expert_revisions")),
        sa.UniqueConstraint("expert_id", "revision_no", name="expert_revision_no"),
    )
    op.create_index(
        op.f("ix_expert_revisions_content_sha256"),
        "expert_revisions",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expert_revisions_expert_id"), "expert_revisions", ["expert_id"], unique=False
    )
    op.create_table(
        "skill_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("content_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_review', 'approved', "
            "'rejected', 'published', 'archived')",
            name=op.f("ck_skill_revisions_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_revisions_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_revisions")),
        sa.UniqueConstraint("skill_id", "revision_no", name="skill_revision_no"),
    )
    op.create_index(
        op.f("ix_skill_revisions_content_sha256"),
        "skill_revisions",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_revisions_skill_id"), "skill_revisions", ["skill_id"], unique=False
    )
    op.create_table(
        "revision_tools",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("expert_revision_id", sa.Uuid(), nullable=False),
        sa.Column("tool_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["expert_revision_id"],
            ["expert_revisions.id"],
            name=op.f("fk_revision_tools_expert_revision_id_expert_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision_tools")),
        sa.UniqueConstraint(
            "expert_revision_id", "tool_id", "version", name="uq_revision_tools_row"
        ),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("expert_revision_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("provider_catalog_id", sa.Uuid(), nullable=False),
        sa.Column("provider_model_id", sa.String(length=200), nullable=False),
        sa.Column("provider_key_version", sa.Integer(), nullable=False),
        sa.Column("initial_message_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("input_committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("abort_reason", sa.String(length=60), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('uploading', 'queued', 'running', 'ready', "
            "'completed', 'failed', 'aborted', 'deleted')",
            name=op.f("ck_tasks_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["expert_revision_id"],
            ["expert_revisions.id"],
            name=op.f("fk_tasks_expert_revision_id_expert_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_tasks_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["user_providers.id"],
            name=op.f("fk_tasks_provider_id_user_providers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_id_owner", "tasks", ["id", "owner_id"], unique=False)
    op.create_index("ix_tasks_owner_created", "tasks", ["owner_id", "created_at"], unique=False)
    op.create_index(
        "ix_tasks_queued",
        "tasks",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_table(
        "task_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("round_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('message_saved', 'round_queued', 'round_running', "
            "'round_settled', 'round_failed', 'round_cancelled', 'status_changed')",
            name=op.f("ck_task_events_type_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_events_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_events")),
        sa.UniqueConstraint("task_id", "sequence", name="task_event_sequence"),
    )
    op.create_table(
        "task_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('input', 'output')", name=op.f("ck_task_files_direction_enum")
        ),
        sa.CheckConstraint(
            "position('/' in file_name) = 0 AND position('\\' in file_name) = 0",
            name=op.f("ck_task_files_file_name_single_segment"),
        ),
        sa.CheckConstraint(
            "state IN ('staged', 'committed', 'registered', 'deleted')",
            name=op.f("ck_task_files_state_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_files_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_files")),
    )
    op.create_index(op.f("ix_task_files_task_id"), "task_files", ["task_id"], unique=False)
    op.create_table(
        "task_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("author", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "author IN ('user', 'assistant', 'tool')", name=op.f("ck_task_messages_author_enum")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_messages_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_messages")),
        sa.UniqueConstraint("task_id", "event_sequence", name="task_message_event_sequence"),
    )
    op.create_table(
        "task_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('active', 'running', 'task_root', 'artifact_copy')",
            name=op.f("ck_task_reservations_kind_enum"),
        ),
        sa.CheckConstraint(
            "state IN ('held', 'consumed', 'released')",
            name=op.f("ck_task_reservations_state_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["task_files.id"],
            name=op.f("fk_task_reservations_file_id_task_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_reservations_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_reservations")),
    )
    op.create_index(
        "ix_task_reservations_user_kind_state",
        "task_reservations",
        ["user_id", "kind", "state"],
        unique=False,
    )
    op.create_index(
        "one_live_active_reservation",
        "task_reservations",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'active' AND state IN ('held','consumed')"),
    )
    op.create_index(
        "one_live_artifact_copy_reservation",
        "task_reservations",
        ["task_id", "file_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'artifact_copy' AND state IN ('held','consumed')"),
    )
    op.create_index(
        "one_live_running_reservation",
        "task_reservations",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'running' AND state IN ('held','consumed')"),
    )
    op.create_index(
        "one_live_task_root_reservation",
        "task_reservations",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'task_root' AND state IN ('held','consumed')"),
    )
    op.create_table(
        "task_rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("source_message_id", sa.Uuid(), nullable=False),
        sa.Column("client_request_id", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("lease_owner", sa.String(length=100), nullable=True),
        sa.Column("lease_epoch", sa.Integer(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'running', 'cancelling', 'settled', 'failed', 'cancelled')",
            name=op.f("ck_task_rounds_state_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["task_messages.id"],
            name=op.f("fk_task_rounds_source_message_id_task_messages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_rounds_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_rounds")),
        sa.UniqueConstraint("source_message_id", name="round_source_message"),
    )
    op.create_index(
        "one_active_round_per_task",
        "task_rounds",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('pending','running','cancelling')"),
    )
    # ### end Alembic commands ###

    # ---- 循环外键补建（use_alter 四条）----
    # autogenerate 将 use_alter=True 的 FK 内联渲染在 create_table 中，但 op.create_table
    # 单表建表不执行内联 use_alter 约束（实测全部缺失）——显式建约束，
    # 约束名与元数据命名约定 fk_(table)_(column)_(referred_table) 一字不差。
    op.create_foreign_key(
        "fk_platform_slots_task_id_tasks",
        "platform_slots",
        "tasks",
        ["task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_experts_published_revision_id_expert_revisions",
        "experts",
        "expert_revisions",
        ["published_revision_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_skills_published_revision_id_skill_revisions",
        "skills",
        "skill_revisions",
        ["published_revision_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_tasks_initial_message_id_task_messages",
        "tasks",
        "task_messages",
        ["initial_message_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ---- 角色（幂等，单条 DO 块允许整体一个 op.execute）----
    op.execute("""
    DO $$ BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='agentcraft_app') THEN
        CREATE ROLE agentcraft_app LOGIN PASSWORD 'change-me-app-local';
      END IF;
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='agentcraft_admin') THEN
        CREATE ROLE agentcraft_admin LOGIN PASSWORD 'change-me-admin-local';
      END IF;
    END $$;
    """)
    op.execute("REVOKE CREATE ON SCHEMA public FROM PUBLIC")
    op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC")
    op.execute("GRANT USAGE ON SCHEMA public TO agentcraft_app")
    op.execute("GRANT USAGE ON SCHEMA public TO agentcraft_admin")
    # ---- owner 上下文函数（逐条执行）----
    from backend.v2.db import OWNER_FN_STATEMENTS

    for stmt in OWNER_FN_STATEMENTS:
        op.execute(stmt)
    op.execute("GRANT USAGE ON SCHEMA app TO agentcraft_app")
    op.execute("GRANT USAGE ON SCHEMA app TO agentcraft_admin")
    op.execute("GRANT EXECUTE ON FUNCTION app.set_current_owner(uuid) TO agentcraft_app")
    op.execute("GRANT EXECUTE ON FUNCTION app.set_current_owner(uuid) TO agentcraft_admin")
    op.execute("GRANT EXECUTE ON FUNCTION app.current_owner_id() TO agentcraft_app")
    op.execute("GRANT EXECUTE ON FUNCTION app.current_owner_id() TO agentcraft_admin")

    # ---- 表级授权白名单（DB §3.1 授权矩阵）----
    _APP_DML = [
        "tasks",
        "task_files",
        "task_messages",
        "task_rounds",
        "task_events",
        "user_providers",
        "sessions",
        "account_action_tokens",
        "email_outbox",
        "reports",
        "experts",
        "expert_revisions",
        "skills",
        "skill_revisions",
        "revision_tools",
        "user_quotas",
        "user_quota_usage",
        "usage_daily",
        "task_reservations",
        "platform_slots",
        "platform_storage",
        "idempotency_records",
        "rate_limit_events",
    ]
    _APP_READ = ["provider_catalog", "tool_catalog", "invitations"]  # 只读：目录与邀请
    for t in _APP_DML:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO agentcraft_app")
    for t in _APP_READ:
        op.execute(f"GRANT SELECT ON {t} TO agentcraft_app")
    # content_reviews / audit_logs：app role 无任何权限（审核与审计属管理面）
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO agentcraft_admin"
    )
    # ---- 序列（本库无 identity 序列，UUIDv7 应用侧生成；保险起见显式放弃 PUBLIC 默认）----

    # ---- owner RLS（9 张表；owner/user 列名映射）----
    owner_tables = [
        ("tasks", "owner_id"),
        ("task_files", "owner_id"),
        ("task_messages", "owner_id"),
        ("task_rounds", "owner_id"),
        ("task_events", "owner_id"),
        ("user_providers", "user_id"),
        ("sessions", "user_id"),
        ("account_action_tokens", "user_id"),
        ("email_outbox", "user_id"),
    ]
    for table, col in owner_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        for action in ("SELECT", "INSERT", "UPDATE", "DELETE"):
            using = (
                f"USING ({col} = app.current_owner_id())"
                if action in ("SELECT", "UPDATE", "DELETE")
                else ""
            )
            check = (
                f"WITH CHECK ({col} = app.current_owner_id())"
                if action in ("INSERT", "UPDATE")
                else ""
            )
            op.execute(
                f"CREATE POLICY {table}_app_{action.lower()} ON {table} FOR {action} "
                f"TO agentcraft_app {using} {check};"
            )
        op.execute(
            f"CREATE POLICY {table}_admin_read ON {table} FOR SELECT "
            f"TO agentcraft_admin USING (true);"
        )

    # ---- 特例：experts / skills（终审 F2：owner RLS + 发布可见性）----
    # 不进上面的 owner_tables 循环，逐表手工建模，与循环模板的两点差异：
    # 1. SELECT 对 status='published' 放行（陌生 owner / 无上下文 guest 可读
    #    公开目录）——纯 owner 匹配会把已发布内容对陌生人隐藏；
    # 2. UPDATE/DELETE 的 USING 仅匹配 owner 本人 → 跨 owner 发布指针劫持
    #    （published_revision_id 改写）与级联删除他人 revision 被静默 0 行拒绝。
    # admin 侧与 owner 表一致：仅 admin_read 全量 SELECT（UPDATE/DELETE 无适用
    # policy → 静默 0 行；处置类写操作经应用层以 superuser/专用角色执行）。
    for pub_table in ("experts", "skills"):
        op.execute(f"ALTER TABLE {pub_table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {pub_table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"CREATE POLICY {pub_table}_app_select ON {pub_table} FOR SELECT "
            f"TO agentcraft_app "
            f"USING (status = 'published' OR {pub_table}.owner_id = app.current_owner_id());"
        )
        op.execute(
            f"CREATE POLICY {pub_table}_app_insert ON {pub_table} FOR INSERT "
            f"TO agentcraft_app WITH CHECK (owner_id = app.current_owner_id());"
        )
        op.execute(
            f"CREATE POLICY {pub_table}_app_update ON {pub_table} FOR UPDATE "
            f"TO agentcraft_app "
            f"USING (owner_id = app.current_owner_id()) "
            f"WITH CHECK (owner_id = app.current_owner_id());"
        )
        op.execute(
            f"CREATE POLICY {pub_table}_app_delete ON {pub_table} FOR DELETE "
            f"TO agentcraft_app USING (owner_id = app.current_owner_id());"
        )
        op.execute(
            f"CREATE POLICY {pub_table}_admin_read ON {pub_table} FOR SELECT "
            f"TO agentcraft_admin USING (true);"
        )

    # ---- 特例：expert_revisions / skill_revisions / reports ----
    # revision 表冗余 owner_id 列（Task 4 已定义，插入时由服务层从 parents 表写入）→ 直接 RLS
    for rev_table, parent in (("expert_revisions", "experts"), ("skill_revisions", "skills")):
        op.execute(f"ALTER TABLE {rev_table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"CREATE POLICY {rev_table}_app_all ON {rev_table} FOR ALL TO agentcraft_app "
            f"USING ({rev_table}.owner_id = app.current_owner_id()) "
            f"WITH CHECK ({rev_table}.owner_id = app.current_owner_id());"
        )
        op.execute(
            f"CREATE POLICY {rev_table}_app_published_read ON {rev_table} "
            f"FOR SELECT TO agentcraft_app "
            f"USING (EXISTS (SELECT 1 FROM {parent} p "
            f"WHERE p.published_revision_id = {rev_table}.id));"
        )
        op.execute(
            f"CREATE POLICY {rev_table}_admin_read ON {rev_table} FOR SELECT "
            f"TO agentcraft_admin USING (true);"
        )
    op.execute("ALTER TABLE reports ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY reports_app_all ON reports FOR ALL TO agentcraft_app "
        "USING (reporter_id = app.current_owner_id()) "
        "WITH CHECK (reporter_id = app.current_owner_id())"
    )
    # admin 侧：读全量 + 处置（resolve 动作改 status，需 UPDATE policy——RLS 下无适用
    # policy 的 UPDATE 可见 0 行；WITH CHECK 省略时默认同 USING，即恒真）
    op.execute(
        "CREATE POLICY reports_admin_read ON reports FOR SELECT TO agentcraft_admin USING (true)"
    )
    op.execute(
        "CREATE POLICY reports_admin_update ON reports FOR UPDATE TO agentcraft_admin USING (true)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ---- 循环外键先删（否则 drop_table 循环对相互阻塞：task_messages↔tasks 等）----
    op.drop_constraint("fk_tasks_initial_message_id_task_messages", "tasks", type_="foreignkey")
    op.drop_constraint(
        "fk_skills_published_revision_id_skill_revisions", "skills", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_experts_published_revision_id_expert_revisions", "experts", type_="foreignkey"
    )
    op.drop_constraint("fk_platform_slots_task_id_tasks", "platform_slots", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "one_active_round_per_task",
        table_name="task_rounds",
        postgresql_where=sa.text("state IN ('pending','running','cancelling')"),
    )
    op.drop_table("task_rounds")
    op.drop_index(
        "one_live_task_root_reservation",
        table_name="task_reservations",
        postgresql_where=sa.text("kind = 'task_root' AND state IN ('held','consumed')"),
    )
    op.drop_index(
        "one_live_running_reservation",
        table_name="task_reservations",
        postgresql_where=sa.text("kind = 'running' AND state IN ('held','consumed')"),
    )
    op.drop_index(
        "one_live_artifact_copy_reservation",
        table_name="task_reservations",
        postgresql_where=sa.text("kind = 'artifact_copy' AND state IN ('held','consumed')"),
    )
    op.drop_index(
        "one_live_active_reservation",
        table_name="task_reservations",
        postgresql_where=sa.text("kind = 'active' AND state IN ('held','consumed')"),
    )
    op.drop_index("ix_task_reservations_user_kind_state", table_name="task_reservations")
    op.drop_table("task_reservations")
    op.drop_table("task_messages")
    op.drop_index(op.f("ix_task_files_task_id"), table_name="task_files")
    op.drop_table("task_files")
    op.drop_table("task_events")
    op.drop_index(
        "ix_tasks_queued", table_name="tasks", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_index("ix_tasks_owner_created", table_name="tasks")
    op.drop_index("ix_tasks_id_owner", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("revision_tools")
    op.drop_index(op.f("ix_skill_revisions_skill_id"), table_name="skill_revisions")
    op.drop_index(op.f("ix_skill_revisions_content_sha256"), table_name="skill_revisions")
    op.drop_table("skill_revisions")
    op.drop_index(op.f("ix_expert_revisions_expert_id"), table_name="expert_revisions")
    op.drop_index(op.f("ix_expert_revisions_content_sha256"), table_name="expert_revisions")
    op.drop_table("expert_revisions")
    op.drop_table("user_quotas")
    op.drop_table("user_quota_usage")
    op.drop_index(
        "uq_user_providers_one_default",
        table_name="user_providers",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_index(op.f("ix_user_providers_user_id"), table_name="user_providers")
    op.drop_table("user_providers")
    op.drop_index(
        "one_active_entitlement",
        table_name="user_entitlements",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("user_entitlements")
    op.drop_table("usage_daily")
    op.drop_index(op.f("ix_skills_owner_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("reports")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_index(
        "invitations_one_open_email",
        table_name="invitations",
        postgresql_where=sa.text("consumed_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_table("invitations")
    op.drop_index(op.f("ix_experts_owner_id"), table_name="experts")
    op.drop_table("experts")
    op.drop_table("email_outbox")
    op.drop_index("ix_content_reviews_target_hash", table_name="content_reviews")
    op.drop_table("content_reviews")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_account_action_tokens_token_hash"), table_name="account_action_tokens")
    op.drop_table("account_action_tokens")
    op.drop_table("users")
    op.drop_table("tool_catalog")
    op.drop_index("ix_rate_limit_scope_subject_time", table_name="rate_limit_events")
    op.drop_table("rate_limit_events")
    op.drop_table("provider_catalog")
    op.drop_table("platform_storage")
    op.drop_index("ix_platform_slots_task_id", table_name="platform_slots")
    op.drop_index("ix_platform_slots_state_leased_until", table_name="platform_slots")
    op.drop_table("platform_slots")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
    # ---- owner 上下文函数随 app schema 删除（roles 保留：幂等创建的集群级对象）----
    op.execute("DROP SCHEMA IF EXISTS app CASCADE")
