"""add user_providers and task provider snapshot

Revision ID: 2906d805fc72
Revises: 81c5eaa9f910
Create Date: 2026-09-03 14:58:43.274900

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2906d805fc72"
down_revision: Union[str, Sequence[str], None] = "81c5eaa9f910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("protocol", sa.String(length=20), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("api_key_hint", sa.String(length=8), nullable=True),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("protocol IN ('openai')", name="ck_user_providers_protocol"),
        sa.CheckConstraint("is_default IN (0,1)", name="ck_user_providers_is_default"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_providers_user_name"),
    )
    op.create_index("idx_user_providers_user_id", "user_providers", ["user_id"], unique=False)
    # SQLite 不支持 ALTER 加约束（含外键），列与 FK 统一走 batch 模式（copy-and-move）
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(sa.Column("provider_config_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("provider_snapshot", sa.Text(), nullable=False, server_default="{}")
        )
        batch_op.create_foreign_key(
            "fk_tasks_provider_config_id",
            "user_providers",
            ["provider_config_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_constraint("fk_tasks_provider_config_id", type_="foreignkey")
        batch_op.drop_column("provider_snapshot")
        batch_op.drop_column("provider_config_id")
    op.drop_index("idx_user_providers_user_id", table_name="user_providers")
    op.drop_table("user_providers")
    # ### end Alembic commands ###
