"""add documented indexes

Revision ID: 81c5eaa9f910
Revises: 1dfe54d34fc0
Create Date: 2026-09-02 11:36:34.971044

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c5eaa9f910"
down_revision: Union[str, Sequence[str], None] = "1dfe54d34fc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_expert_mcps_server_id", "expert_mcps", ["server_id"], unique=False)
    op.create_index("idx_expert_skills_skill_id", "expert_skills", ["skill_id"], unique=False)
    op.create_index("idx_experts_owner_id", "experts", ["owner_id"], unique=False)
    op.create_index("idx_experts_status_category", "experts", ["status", "category"], unique=False)
    op.create_index("idx_mcp_servers_owner_id", "mcp_servers", ["owner_id"], unique=False)
    op.create_index("idx_mcp_tools_server_id", "mcp_tools", ["server_id"], unique=False)
    op.create_index(
        "idx_messages_conv_created", "messages", ["conversation_id", "created_at"], unique=False
    )
    op.create_index("idx_skills_owner_id", "skills", ["owner_id"], unique=False)
    op.create_index(
        "idx_task_files_task_created", "task_files", ["task_id", "created_at"], unique=False
    )
    op.create_index("idx_tasks_expert_id", "tasks", ["expert_id"], unique=False)
    op.create_index("idx_tasks_user_id", "tasks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_user_id", table_name="tasks")
    op.drop_index("idx_tasks_expert_id", table_name="tasks")
    op.drop_index("idx_task_files_task_created", table_name="task_files")
    op.drop_index("idx_skills_owner_id", table_name="skills")
    op.drop_index("idx_messages_conv_created", table_name="messages")
    op.drop_index("idx_mcp_tools_server_id", table_name="mcp_tools")
    op.drop_index("idx_mcp_servers_owner_id", table_name="mcp_servers")
    op.drop_index("idx_experts_status_category", table_name="experts")
    op.drop_index("idx_experts_owner_id", table_name="experts")
    op.drop_index("idx_expert_skills_skill_id", table_name="expert_skills")
    op.drop_index("idx_expert_mcps_server_id", table_name="expert_mcps")
    # ### end Alembic commands ###
