"""聚合出口：alembic_v2 env.py 的 target_metadata 指向 Base.metadata。
新模型必须在此 import 才会进入 autogenerate 视野。"""
from backend.v2.models import catalog, content, identity
from backend.v2.models.base import Base, TimestampMixin, check_enum, pk_uuid
from backend.v2.models.catalog import (
    PROVIDER_STATUSES,
    SLOT_STATES,
    PlatformSlot,
    PlatformStorage,
    ProviderCatalog,
    RateLimitEvent,
    UsageDaily,
    UserProvider,
    UserQuota,
    UserQuotaUsage,
)
from backend.v2.models.content import (
    ENTITY_STATUSES,
    REPORT_STATUSES,
    REVISION_STATUSES,
    AuditLog,
    ContentReview,
    Expert,
    ExpertRevision,
    Report,
    RevisionTool,
    Skill,
    SkillRevision,
    ToolCatalog,
)
from backend.v2.models.identity import (
    ACTION_TOKEN_PURPOSES,
    ENTITLEMENTS,
    OUTBOX_PURPOSES,
    OUTBOX_STATES,
    USER_ROLES,
    USER_STATUSES,
    AccountActionToken,
    EmailOutbox,
    Invitation,
    Session,
    User,
    UserEntitlement,
)

__all__ = [
    "ACTION_TOKEN_PURPOSES",
    "ENTITLEMENTS",
    "ENTITY_STATUSES",
    "OUTBOX_PURPOSES",
    "OUTBOX_STATES",
    "PROVIDER_STATUSES",
    "REPORT_STATUSES",
    "REVISION_STATUSES",
    "SLOT_STATES",
    "USER_ROLES",
    "USER_STATUSES",
    "AccountActionToken",
    "AuditLog",
    "Base",
    "ContentReview",
    "EmailOutbox",
    "Expert",
    "ExpertRevision",
    "Invitation",
    "PlatformSlot",
    "PlatformStorage",
    "ProviderCatalog",
    "RateLimitEvent",
    "Report",
    "RevisionTool",
    "Session",
    "Skill",
    "SkillRevision",
    "TimestampMixin",
    "ToolCatalog",
    "UsageDaily",
    "User",
    "UserEntitlement",
    "UserProvider",
    "UserQuota",
    "UserQuotaUsage",
    "catalog",
    "check_enum",
    "content",
    "identity",
    "pk_uuid",
]
